name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
  MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
  MONGODB_COLLECTION: ${{ secrets.MONGODB_COLLECTION }}
  REACT_APP_TOKEN_MAPBOX: ${{ secrets.REACT_APP_TOKEN_MAPBOX }}

jobs:
  build:

    runs-on: ubuntu-latest
    
    environment: mapa-bibliotecas2
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test-API
      - run: npm run test-react
