name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MONGODB_USERNAME: admin
  MONGODB_PASSWORD: mapa-bibliotecas-PI-2022
  MONGODB_CLUSTER: mapa-cluster
  MONGODB_DATABASE: bibliotecas-db
  MONGODB_COLLECTION: censo2020
  REACT_APP_TOKEN_MAPBOX: pk.eyJ1IjoiZ21lcmVuY2lvIiwiYSI6ImNsMjgyYTVxODA1OXUzZG56emppeHFkd2wifQ.5NMbrQod0tTYWB0CnqqEmA

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test-API
      - run: npm run test-react
